name: Build and Deploy
on:
  workflow_dispatch:
  push:  
    branches:
    - develop
    - main
    

jobs:
  build: 
    name: build on develop
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/develop'
    steps:
      # - name: Build on ${{github.ref_name}}
      #   uses: actions/checkout@v3
      - name: Code Building
        run:  echo "building on dev"

  # deploy:
  #   name: Deploy on ${{github.ref_name}}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: Dev  
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #     - name: Copy Code to AWS S3 Bucket
  #       uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --acl public-read --exclude '.git*/*'
  #       env:
  #         AWS_S3_BUCKET: be-edp-dev-prj
  #         AWS_ACCESS_KEY_ID: ${{ secrets.Dev_AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.Dev_AWS_SECRET_ACCESS_KEY }}

  deployUAT:
    name: Deploy on ${{github.ref_name}}  
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.AWS_UAT }}

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Read UAT env variable 
        run: echo "UAT AWS vars is" ${{ env.MY_APP_ID }}

      - name: UAT
        run: echo "I am in the main branch"
      - name: UAT
        run: echo "Coming from JIRA for Approval"  
 
